name: First workflow
on: push
jobs:
 first-job: 
  runs-on: ubuntu-latest
  steps:
   - name: verify installed java 
     run: java --version
   - name: installing java
     uses: actions/setup-java@v5.1.0
     with:
       java-version: "17"
       distribution: 'tumerin'
       
      
     
